spring:
  application:
    name: shelf
  profiles: shelf
server:
  port: 8000
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
---
spring:
  application:
    name: shelf
  profiles: shelf1
server:
  port: 8001
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8003/eureka/
---
spring:
  application:
    name: shelf
  profiles: shelf2
server:
  port: 8002
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8003/eureka/
---
spring:
  application:
    name: shelf
  profiles: shelf3
server:
  port: 8003
eureka:
  instance:
    hostname: shelf3
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/,http://localhost:8002/eureka/
